<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.geppetto.org/model" nsPrefix="gep">
  <eClassifiers xsi:type="ecore:EClass" name="GeppettoModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//variables/Variable" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" upperBound="-1"
        eType="#//GeppettoLibrary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
    <eOperations name="getPath" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeppettoLibrary" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//types/Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sharedTypes" upperBound="-1"
        eType="#//types/Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LibraryManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" upperBound="-1"
        eType="#//GeppettoLibrary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeppettoModelState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="recordedVariables" upperBound="-1"
        eType="#//VariableValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setParameters" upperBound="-1"
        eType="#//VariableValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pointer" lowerBound="1"
        eType="#//values/Pointer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//values/Value"/>
  </eClassifiers>
  <eSubpackages name="types" nsURI="http://www.geppetto.org/model/types" nsPrefix="gep">
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//Node">
      <eOperations name="getDefaultValue" eType="#//values/Value"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//types/Type"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
          transient="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="visualType" eType="#//types/VisualType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedVariables"
          upperBound="-1" eType="#//variables/Variable" transient="true" resolveProxies="false"
          eOpposite="#//variables/Variable/types"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VisualType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//values/VisualValue"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImportType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceURL" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelInterpreterId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
          eType="#//variables/Variable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//values/Composite"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PointerType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//values/Pointer"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QuantityType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//values/Quantity"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//values/Quantity"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StateVariableType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//values/Quantity"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DynamicsType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//values/Dyamics"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//values/Argument"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExpressionType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//values/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HTMLType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//values/HTML"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//values/Text"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="URLType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//values/URL"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PointType" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//values/Point"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="values" nsURI="http://www.geppetto.org/model/values" nsPrefix="gep">
    <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Composite" eSuperTypes="#//values/Value">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
          eType="#//values/StringToValueMap" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringToValueMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//values/Value"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Quantity" eSuperTypes="#//values/Value">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scalingFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PhysicalQuantity" eSuperTypes="#//values/Quantity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//values/Unit"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Unit" eSuperTypes="#//values/Value">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeSeries" eSuperTypes="#//values/Value">
      <eStructuralFeatures xsi:type="ecore:EReference" name="quantities" upperBound="-1"
          eType="#//values/Quantity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//values/Unit"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MetadataValue" abstract="true" eSuperTypes="#//values/Value"/>
    <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//values/MetadataValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="URL" eSuperTypes="#//values/MetadataValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HTML" eSuperTypes="#//values/MetadataValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="html" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pointer" eSuperTypes="#//values/Value">
      <eOperations name="getValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//values/PointerElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PointerElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//variables/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//types/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Point" eSuperTypes="#//values/Value">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Dyamics" eSuperTypes="#//values/Value">
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialCondition" eType="#//values/PhysicalQuantity"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dynamics" eType="#//values/Function"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//values/Value">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#//values/Argument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//values/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Argument" eSuperTypes="#//values/Value">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="argument" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//values/Value">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VisualValue" abstract="true" eSuperTypes="#//values/Value">
      <eStructuralFeatures xsi:type="ecore:EReference" name="groupElements" upperBound="-1"
          eType="#//values/VisualGroupElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Collada" eSuperTypes="#//values/VisualValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="collada" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VisualComposite" eSuperTypes="#//values/VisualValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
          eType="#//values/VisualValue" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="visualGroups" upperBound="-1"
          eType="#//values/VisualGroup"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OBJ" eSuperTypes="#//values/VisualValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="obj" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sphere" eSuperTypes="#//values/VisualValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="radius" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cylinder" eSuperTypes="#//values/VisualValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bottomRadius" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="topRadius" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="distal" eType="#//values/Point"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Particle" eSuperTypes="#//values/VisualValue #//values/Point"/>
    <eClassifiers xsi:type="ecore:EClass" name="SkeletonAnimation" eSuperTypes="#//values/VisualValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="skeletonTransformationSeries"
          upperBound="-1" eType="#//values/SkeletonTransformation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SkeletonTransformation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="skeletonTransformation"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VisualGroupElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultColor" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//values/Quantity"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VisualGroup">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowSpectrumColor" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="highSpectrumColor" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="visualGroupElements"
          lowerBound="1" upperBound="-1" eType="#//values/VisualGroupElement" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="variables" nsURI="http://www.geppetto.org/model/variables" nsPrefix="gep">
    <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Node">
      <eStructuralFeatures xsi:type="ecore:EReference" name="anonymousTypes" upperBound="-1"
          eType="#//types/Type" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
          eType="#//types/Type" resolveProxies="false" eOpposite="#//types/Type/referencedVariables"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialValues" eType="#//values/Value"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//values/Point"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayVariable" eSuperTypes="#//variables/Variable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
